version: '3.7'

services:
  posweb-dev:
    container_name: pos-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    stdin_open: true
