version: "3.7"

services:
  pos-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pos-api
    volumes:
      - ./src:/home/node/app/src
    expose:
      - "8001"
    ports:
      - "4002:8001"
      - "9229:9229"
    command: npm run start-dev
